name: TDDPractice CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Visual Studio のパスを設定
        shell: powershell
        run: |
          # vswhere.exe のパスが存在するか確認
          $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-not (Test-Path $vswherePath)) { 
            throw "vswhere.exe not found at expected location: $vswherePath"
          }

          # MSBuild のパスを取得
          $msbuildPath = & "$vswherePath" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          if (-not $msbuildPath) { 
            throw "MSBuild path not found. Please check Visual Studio installation or update vswhere query." 
          }
          echo "MSBUILD_PATH=$msbuildPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: NuGet のインストール
        run: nuget restore TDDPractice.sln

      - name: ビルド
        shell: powershell
        run: |
          & "${env:MSBUILD_PATH}" TDDPractice.sln /p:Configuration=Release

      - name: テストの実行
        shell: powershell
        run: |
          $vstestPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
          if (-not (Test-Path $vstestPath)) { throw "vstest.console.exe not found at path: $vstestPath" }
          & "$vstestPath" TDDPractice/TDDPractice.Tests/bin/Release/TDDPractice.Tests.dll /Platform:x64
