name: Build TDDPractice App
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
 
    strategy:
      matrix:
        configuration: [Debug, Release]
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
      
    - name: Restore NuGet Packages
      run: nuget restore TDDPractice.sln
      
    - name: Build TDDPractice App
      run: msbuild TDDPractice.sln /p:Configuration=${{ matrix.configuration }}
 
    - name: Upload GitHub Pages artifact - TDDPractice
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        name: TDDPractice_${{ matrix.configuration }}
        path: TDDPractice\bin\${{ matrix.configuration }}
