# GitHub Actionsの名前
name: Build .NET Framework 4.7.2
# GitHub Actionsを実行させたい動作
on:
  # 今回はpush時に実行させる 
  push:
    # GitHub Actionsを実行させたいブランチを指定する(今回はdevelopを指定)
    branches: [ master ]
# 自動化
jobs:
  build:
    # GitHub Actionsで動作させる仮想OS環境(今回はubuntuを指定)
    runs-on: windows-latest
    # 自動化する動作
    steps:
      # プロジェクトをチェックアウトする
      - name: checkout
        uses: actions/checkout@v2
     # .Net のRuntimeを仮想OSにインストールする
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          # インストール.netのバージョンを指定(今回は.net6.0を指定) 
          dotnet-version: 4.7.2
      # プロジェクトで必要なライブラリなどをインストールする
      - name: Restore dependencies
        run: dotnet restore
      # ビルドを行う(同時にコーティング規約の静的チェックを行う)
      - name: DotNet Build Restore
        run: dotnet build --no-restore /warnaserror
      # ユニットテストを行う
      - name: DotNet Unit Test
        run: dotnet test
