name: TDDPractice CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: NuGetのインストール
        run: nuget restore TDDPractice.sln

      - name: Visual Studioのパスを設定
        shell: powershell
        run: |
          # vswhere.exe のパスが存在するか確認
          $vswherePath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-not (Test-Path $vswherePath)) { 
            throw "vswhere.exe not found at expected location: $vswherePath"
          }

          # MSBuildのパスを取得
          $vsPath = & "$vswherePath" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          if (-not $vsPath) { 
            throw "MSBuild path not found. Please check Visual Studio installation or update vswhere query." 
          }
          echo "MSBUILD_PATH=$vsPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          
          # vstest.console.exe のパスを取得
          $vstestPath = & "$vswherePath" -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools -find Common7\IDE\Extensions\TestPlatform\vstest.console.exe
          if (-not $vstestPath) {
            $vstestPath = & "$vswherePath" -latest -products * -find Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
          }
          if (-not $vstestPath) { 
            throw "vstest.console.exe path not found. Please check Visual Studio installation or update vswhere query."
          }
          echo "VSTEST_PATH=$vstestPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: ビルド
        shell: powershell
        run: |
          if (-not (Test-Path "$env:MSBUILD_PATH")) { throw "MSBuild path is invalid or empty: $env:MSBUILD_PATH" }
          & "$env:MSBUILD_PATH" TDDPractice.sln /p:Configuration=Release

      - name: テストの実行
        shell: powershell
        run: |
          if (-not (Test-Path "$env:VSTEST_PATH")) { throw "vstest.console.exe path is invalid or empty: $env:VSTEST_PATH" }
          & "$env:VSTEST_PATH" TDDPractice/TDDPractice.Tests/bin/Release/TDDPractice.Tests.dll /Platform:x64
