name: TDDPractice CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: NuGetのインストール
        run: nuget restore TDDPractice.sln

      - name: ビルド
        run: msbuild TDDPractice.sln /p:Configuration=Release

      - name: テストの実行
        run: vstest.console.exe TDDPractice/TDDPractice.Tests/bin/Release/TDDPractice.Tests.dll /Platform:x64
