name: TDDPractice CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: .NET Frameworkのビルドとテスト
        run: |
          nuget restore TDDPractice.sln
          msbuild TDDPractice.sln /p:Configuration=Release
          vstest.console.exe ./path/to/YourTestProject.dll /Platform:x64
