name: TDDPractice CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: NuGetのインストール
        run: nuget restore TDDPractice.sln

      - name: Visual Studioのパスを設定
        shell: powershell
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          if (-not $vsPath) { throw "MSBuildのパスが見つかりませんでした。" }
          echo "MSBUILD_PATH=$vsPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          
          $vstestPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.TestTools.BuildTools -find Common7\IDE\Extensions\TestPlatform\vstest.console.exe
          if (-not $vstestPath) { throw "vstest.console.exeのパスが見つかりませんでした。" }
          echo "VSTEST_PATH=$vstestPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: ビルド
        shell: powershell
        env:
          MSBUILD_PATH: ${{ env.MSBUILD_PATH }}
        run: |
          if (-not (Test-Path "${env:MSBUILD_PATH}")) { throw "MSBuildのパスが無効です: $env:MSBUILD_PATH" }
          & "${env:MSBUILD_PATH}" TDDPractice.sln /p:Configuration=Release

      - name: テストの実行
        shell: powershell
        env:
          VSTEST_PATH: ${{ env.VSTEST_PATH }}
        run: |
          if (-not (Test-Path "${env:VSTEST_PATH}")) { throw "vstest.console.exeのパスが無効です: $env:VSTEST_PATH" }
          & "${env:VSTEST_PATH}" TDDPractice/TDDPractice.Tests/bin/Release/TDDPractice.Tests.dll /Platform:x64
